flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- ansi-terminal-0.10.3
- ansi-wl-pprint-0.6.9
- async-2.2.2
- call-stack-0.2.0
- clock-0.8
- colour-2.3.5
- hashable-1.3.0.0
- logict-0.7.0.2
- mintty-0.1.2
- optparse-applicative-0.15.1.0
- QuickCheck-2.14.1
- random-1.2.0
- smallcheck-1.2.0
- splitmix-0.1.0.1
- tagged-0.8.6
- tasty-1.3.1
- tasty-hunit-0.10.0.2
- tasty-quickcheck-0.10.1.1
- tasty-smallcheck-0.8.1
- transformers-compat-0.6.5
- unbounded-delays-0.1.1.0
resolver: ghc-8.10.1
system-ghc: true
allow-newer: true
