flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- QuickCheck-2.8.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.0
- clock-0.7.2
- logict-0.6.0.2
- optparse-applicative-0.12.1.0
- parsec-3.1.11
- primitive-0.6.1.0
- regex-base-0.93.2
- regex-tdfa-1.2.2
- safe-0.3.9
- singletons-2.2
- smallcheck-1.1.1
- stm-2.4.4.1
- syb-0.6
- tagged-0.8.4
- tasty-0.11.0.3
- tasty-hunit-0.9.2
- tasty-quickcheck-0.8.4
- tasty-smallcheck-0.8.1
- text-1.2.2.1
- tf-random-0.5
- th-desugar-1.6
- th-expand-syns-0.4.0.0
- th-lift-0.7.6
- th-lift-instances-0.1.9
- th-orphans-0.13.1
- th-reify-many-0.1.6
- transformers-compat-0.5.1.4
- unbounded-delays-0.1.0.9
- vector-0.11.0.0
resolver: ghc-8.0.1
